### ISSUE TITLE
Installing whitebox tools gets the dev version - FlightlineOverlap fails

### ISSUE THREAD

**Issue by cflynn8** [opengeos/whitebox-python#61]
* whitebox version: 0.8.0.dev0
* Python version: 3.9.16
* Operating System: Windows

### Description

I am trying to run the flightline overlap tool within a function in a larger python script. I have run it fine on my computer that I installed whitebox tools on more than a year ago (it is using whitebox version 2.1.2), but I had to get it setup for someone else and had to have them install whitebox tools. We used the conda install line from the anaconda website (https://anaconda.org/conda-forge/whitebox_tools): "conda install -c conda-forge whitebox_tools". After successfully installing, I checked the version and was surprised that it was 0.8.0.dev0. The first thing that was different when using it was just importing the module. In my scripts I could use "import whitebox" and on the computer with the new install of whitebox it has to be imported with "import whitebox_tools". When I run FlightlineOverlap on my computer I get the expected/correct outputs. On the new install I get this error: 

[WinError 2] The system cannot find the file specified

### What I Did

```
import os
try:
    import whitebox
except:
    import whitebox_tools as whitebox
wbt = whitebox.WhiteboxTools()

lidar_dir = r"path\to\lidar"
raster_dir = r"path\to\raster"
pre_name="Test"

# Create overlap raster for lidar swaths.
def create_overlap(lidar_dir, pre_name, raster_dir):
    print("Creating overlap raster...")
    overlap_raster = os.path.join(raster_dir, pre_name+"_Overlap.tif")

    wbt.set_working_dir(lidar_dir)
    wbt.flightline_overlap(i=None, output=overlap_raster, resolution=1)

    print("Overlap raster created.")
    return overlap_raster

create_overlap(lidar_dir, pre_name, raster_dir)
```
Again, I get this error when running: 
[WinError 2] The system cannot find the file specified

Thanks in advance!

**Comment by giswqs** [comment]
You should install `whitebox`, not `whitebox_tools`
```bash
conda install -c conda-forge whitebox
```
https://anaconda.org/conda-forge/whitebox
