### ISSUE TITLE
wbe.contours_from_raster doesn't work

### ISSUE THREAD

**Issue by vitorbarbosamelo** [opengeos/whitebox-python#62]
whitebox version: whitebox-workflows 1.1.0
Python version: 3.11
Operating System: Windows 

I am trying to generate contour curves from the following code:

import whitebox_workflows as wbw
wbe = wbw.WbEnvironment()

raster = wbe.read_raster('test.tif')

wbe.contours_from_raster(
    raster, 
    'contours.shp', 
    contour_interval = 10,
    base_contour = 57
)

However, the following error appears:
TypeError: WbEnvironment.contours_from_raster() got multiple values for argument 'contour_interval'

I tried using the default value, however the following error appears:
TypeError: argument 'contour_interval': must be real number, not str

**Comment by giswqs** [comment]
This repo is not for whitebox_workflows. Please open an issue at https://github.com/jblindsay/whitebox-tools/issues
