### ISSUE TITLE
Whitebox 2.3.3 (Python): Unrecognized tool name ConditionalEvaluation

### ISSUE THREAD

**Issue by geotom** [opengeos/whitebox-python#67]
* whitebox version:
* Python version: 2.3.3
* Operating System: Unix

This was first posted on the whitebox tracker (https://github.com/jblindsay/whitebox-tools/issues/411)

### Description

I noticed that since the recent release 2.3.3 on PyPi (https://pypi.org/project/whitebox/2.3.3/) a script of mine fails with the following whitebox debug logs

```
./whitebox_tools --run="ConditionalEvaluation" --wd="/celery" --input='a.tif' --statement=value == minvalue && value < -1000 - -true='b.tif' -v --compress_rasters=True
thread 'main' panicked at whitebox-tools-app/src/main.rs:72:21:
Unrecognized tool name ConditionalEvaluation.
run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### What I Did

The code has not changed and calls this function as follows:

```
wbt.conditional_evaluation(
                                "a.tif",
                                "b.tif",
                                statement="value == minvalue && value < -1000",
                                true="source.tif",
                                false="a.tif",
                            )
```
What could the issue be?

**Comment by giswqs** [comment]
I can confirm that this is a WBT backend issue. 

![image](https://github.com/opengeos/whitebox-python/assets/5016453/f9f8c032-0f1b-46fc-9e29-753c12c19bd0)

**Comment by giswqs** [comment]
I fount that both the `ConditionalEvaluation` and `ConditionedLatinHypercube` tools have the same issue. It seems the tools with the word `Condition` have this problem. Other tools are fine.

**Comment by giswqs** [comment]
This bug has been fixed. Please update to the latest v2.3.4

![image](https://github.com/opengeos/whitebox-python/assets/5016453/aa7b65b8-ef1d-4440-beaf-ccc0d5b53d75)
